# Generated by Django 5.0.1 on 2024-01-28 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
    ]
